language: node_js

branches:
  only:
    - publish_wd

env:
  global:
    - URL="https://raw.githack.com/w3c/audiobooks/publish_wd/snapshot/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-07-08-pwg#resolution4"
    - secure: "M0BjKqZCn41PMkQYsVpP6uXYmqUUMSGCQA6q1MRUQdzDI0mPzyDBc4TailO/6qoQuOeSR1RI5XqbBc87WI+QGz960kiDjzUuK9QhRVcI2CbQO8r0Y9Yavolpnt/JuiGNS7NHRdupI2GK9TR/6WKLJf7FdSZyiczV55G8CTyQhc3/y67dQqZyalgc04QOUn3v6gjnn7WVoEd3yavblLvdzG8Im4NKSiVTBtzW4jsb+rC6L+2XzsU0tdGCa44FS4ke8j8cE3VmWXdfMXGOeOCQqkr8raLEXIAFOpYn6NN1ENF+UWcJACrJFFUpEVJklDm1T68V6tOaTEExHi5s5wecEXSXbhQNttFVKVsvH8/kHCupsJjHcQZZjptfhdYKacS+9qOezcpeJ0oncj6lMUojOH9UhtnxzFEuZZnVHxYucMvK54SA0WbSIomK7c06AjWeBCFzwcn7sCOC/qgKyblYPhn1QKLWtlPjuiP7lI7RBy5d+t+GJdluwPe0HBvA8zas/3u3MuhimHidW6LOXJ/dCBjikz3gqT/bH6Jzf5Z3JMElF/uCTUEK1TxtR2aq4xjdOQnbhGY8TrxqjdTnNMPwPL5QKU/aL97hFYKx7ZPn52HIBrXV1SeLuyniok9g+8id3P879sOdAFauRKvy1UIpfsoHzfjTpqRTEfJKj6E5P00="

script:
  - echo "ok"

after_success:
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
