dist: trusty
language: node_js
node_js:
    - lts/*

cache: false

branches:
  only:
    - publish_wd

env:
  global:
    - URL="https://raw.githack.com/w3c/audiobooks/publish_wd/snapshot/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-07-08-pwg#resolution4"
    - secure: "Jf1NPq+jjkmxfgjaogjdZsJVZifNMhqfUmfXITxqcPTXLYTWWGdtIifUnhu/Fvdmjv82snvLVh0oV65oSADjvL3abAaTQsq7EBU+r8Wr9pgXk4TkfWmcH0ARMh1EQ8vvcpN82GyLi4KxrQ2B0G97WVnahZ+3BDWHP5uLC+dwyoP5VYfnXjr/usAuq32Nb+Q0EevxkLGnagDGPiOiFR1YNDUfvNFb4UF6AfdjOB49NE94/aRehldcvJp4431dOI0LYAK0d+jjlqzt7Z4Ny/QgLTQhq80ZlLEiFIEl8Nd155vnuyHmR22bH7epbnOAhjYKKRDp4vuV5j1cWNGKvaFN3lKzcuzauETazaQMbjr0/uQ8OoEV96gwjQn98Resp1cf+zpNfgUwCq0zi9IDfTsH0Wafz1EkGWdlUt/MGL0CuxyAgYR6PtqNBXiTx3x8U/A5XUH6pm4GOox+o0uGjiD1wIP9uxxEfAmiOVdGMhzUNV/N8ievFfgSAYoH8P9VoU37ZtTPFgIpP0mUngiRwds5n/ss3Rkbd7Iw//LP/E003zatIXvP9Yc9dMHoUEtNpHYAd2wScV1J+KjMMWPjSE6F4i3pbTk1B9ZzD6uci1n08RbIoiP/QbpZY4FcePlMC8Iwpzpzp60GMzDBRdDXM9JYlt7R8v8PLSLcaejigna9m0E="

script:
  - echo "ok"

after_success:
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN" --data "editorial=true"
