dist: trusty
language: node_js
node_js:
    - lts/*

branches:
  only:
    - publish_wd

env:
  global:
    - URL="https://raw.githack.com/w3c/audiobooks/publish_wd/snapshot/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-07-08-pwg#resolution4"
    - secure: "vIAw+dx9dmCDVhdwVJgAUj1h6E2ObxEFMs5dJNpHxNfPcrTvjQyQ1UyE20jRkIWLP/0VEw/O2VzoZO3Cu/ZQ9ZaHlzbob6yKHuYsDgapKIAv7AH5Bjx9gnfxQIdmaIArlgTSAdoUwwfVNw1i0t2k4tuAVldRXcGUX+WwLfpyJIIpXuNzIpIyGbhS3FIY1PQTSqmOE6Yl7zF7MONC+T1chb8l1ZEGO/+Fu40bgeAbUWPE0yn1882n6K+CnDDcscKLv1HqsHVSaDG5E4zsJRdT38Ypii8+BmPVuKT2a+ObqVPNlGKg5P35YvQP7b74k1kMOKVLl/4OlYruen+kk2wjcNBg2Br6DFARywhta6vbWENgBQLqDC9Tm2vm69YFjAE0kiX2dfLt0ytnH2c12oN7QB6EKhlb7coEbiBctp0adyYsm4pL7mkhoBOTXK83DdMHoein85HClmin0VyHEZPXC316RCd6QvOe9NHZu8tERVb0NfFOGYLBBiCjclm6385m/w/Bn4Ki56SuNz3XYUGNg/k+4WbJCozLQ33DsMhmEwQKjq/UUtGK2BJazIYj2lasamL4QaLrt/n/WHKS7f3LxFoAG11t6rrpgPuEfWG9rZqyX3viIIH43CUARL+GMwawt2OZ2hXWnq9+q5XgEuQfpFltHWc+juuE+iNvPI3y4uY="

script:
  - echo "ok"

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"'
