dist: trusty
language: node_js
node_js:
    - lts/*

branches:
  only:
    - publish_wd

env:
  global:
    - URL="https://raw.githack.com/w3c/audiobooks/publish_wd/snapshot/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-07-08-pwg#resolution4"
    - secure: ZkPeIjgrWgZIF3oS7FjbOMts53gBhWgjIKz9TSlgCEjfe+LkM1SA1zDUwq5Ma69pDvYhQ+FNJHjkwMyI7Kaxzb1hkoWvc/xZk8GZDoHKB0FP0v5Ukkv5Dm6PeWsyZdH5weZzl77nz2YXhBUytKQZ8ICc9hL5rksngR2g++QZh/4PDltL57riqZGnpALaNqJ5Dg+I3lFLtLG8SZczbEEDR5Y43BHxwuxuhW1m1Lf0/cjgRkfl8uuNhukZFTNFKnmARXYALEBnLT5wNDB+L0lI6TDv9qxzlneFUbP6eFJ1w2aaWwxSHQA3N6/CgfXsFd/qPIkpt6DdNmPOvouK8yAJygrX9V/NZRLSR8m/ysA7Rqa2/7hoW+CIRH9it/SipHW57jUqP9yN85U91SRhD2b73woJcW2bKduUpSnURsfObsA6IMfYovn0NL72k4HRyuPsFWqW4IOnU574zW/LJqtRf4nZnmUgCTCmOtvUjfzZc0D+biVnFykwOum4xFe9ihQ2dcsuBab/hoRfkbPcta6NoTS9tepzbWFLgVZ5WQRY1/5GS7lErpii8w4UD/YGwu8stRo2RtzkRT3TnyWsiw05nIyq6AAayj/oB5Vhfy4DVQU/R0ZiS+eqq/Q8j9WGeyGEebB+MvsreIVtDtmyEXKHmqbUPJfPCpdpEHFvTU7sNqE=

script:
  - echo "ok"

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"'
